((nil . ((indent-tabs-mode . nil)
         (fill-column . 80)
         (sentence-end-double-space . t)
         (emacs-lisp-docstring-fill-column . 75)
         (checkdoc-arguments-in-order-flag . nil))))
