= Using Other ClojureScript REPLs

While these days most people are using `figwheel` and `shadow-cljs`,
CIDER supports other ClojureScript REPLs as well.
This section of the user manual is dedicated to them.

== Browser-Connected ClojureScript REPL

Using Weasel, you can also have a browser-connected REPL.

. Add `[weasel "0.7.0"]` to your project's `:dependencies`.
. Type kbd:[M-x] `cider-jack-in-cljs` kbd:[RET] and choose
the `Weasel` option when prompted about the ClojureScript REPL type you want
to use.
. Add this to your ClojureScript code:
+
[source,clojure]
----
(ns my.cljs.core
  (:require [weasel.repl :as repl]))
(repl/connect "ws://localhost:9001")
----
+
. Open a file in your project and type kbd:[M-x] `cider-jack-in-cljs`.

Provided that a Piggieback-enabled ClojureScript environment is active in your
REPL session, code loading and evaluation will work seamlessly regardless of the
presence of the `cider-nrepl` middleware. If the middleware is present then most
other features of CIDER will also be enabled (including code completion,
documentation lookup, the namespace browser, and macroexpansion).

== Browser-Connected ClojureScript REPL in Boot Projects

. Add this to your dependencies in `build.boot`:
+
[source,clojure]
----
[adzerk/boot-cljs        "X.Y.Z"  :scope "test"]
[adzerk/boot-cljs-repl   "X.Y.Z"  :scope "test"]
[pandeiro/boot-http      "X.Y.Z"  :scope "test"]
[weasel                  "0.7.0"  :scope "test"]
[cider/piggieback "0.4.2"  :scope "test"] ; not needed for cider-jack-in-cljs
----
+
and this at the end of `build.boot`:
+
[source,clojure]
----
(require
 '[adzerk.boot-cljs :refer [cljs]]
 '[adzerk.boot-cljs-repl :refer [cljs-repl]]
 '[pandeiro.boot-http :refer [serve]])

(deftask dev []
  (comp (serve)
        (watch)
        (cljs-repl) ; order is important!!
        (cljs)))
----
+
. Type kbd:[M-x] `customize-variable` kbd:[RET] `cider-boot-parameters`
and insert `dev`.
. Open a file in your project and type kbd:[M-x] `cider-jack-in-cljs`.
. Connect to the running server with your browser. The address is printed on the terminal, but it's probably `+http://localhost:3000+`.

For more information visit https://github.com/adzerk-oss/boot-cljs-repl[boot-cljs-repl].
