= Inspector
:experimental:

The value inspector allows you inspect and navigate the structure of data. While you can use
it for pretty much anything (e.g. primitive data types, var, ref types) it's most
useful when you're dealing with (deeply) nested collection-like data types (e.g. a vector of maps).

== Usage

Typing kbd:[C-c M-i] (`cider-inspect`) after some form in a source
buffer or the REPL will show you the structure for the result of the
form in a new buffer. You can also use kbd:[C-u C-c M-i] to inspect
the result of the current top-level form and kbd:[C-u C-u C-c M-i] to
read an expression from the minibuffer and inspect its result.

Alternatively, after a regular eval command, you can inspect the last
evaluated value using `cider-inspect-last-result`. When a inspector
buffer is visible in the background, it is automatically updated with
the last result. This behavior can be controlled with the variable
`cider-auto-inspect-after-eval`.

TIP: The inspector can also be invoked in the middle of a debugging
session, see xref:debugging/debugger.adoc[here] for more details.

You'll have access to additional keybindings in the inspector buffer
(which is internally using `cider-inspector-mode`):

|===
| Keyboard shortcut | Description

| kbd:[Tab] and kbd:[Shift-Tab]
| Navigate inspectable sub-objects

| kbd:[Return]
| Inspect sub-objects

| kbd:[l]
| Pop to the parent object

| kbd:[g]
| Refresh the inspector (e.g. if viewing an atom/ref/agent)

| kbd:[SPC]
| Jump to next page in paginated view

| kbd:[M-SPC]
| Jump to previous page in paginated view

| kbd:[s]
| Set a new page size in paginated view

| kbd:[c]
| Set a new maximum size above which nested collections are truncated

| kbd:[a]
| Set a new maximum length above which nested atoms (non-collections) are truncated

| kbd:[d]
| Defines a var in the REPL namespace with current inspector value
|===

== Configuration

By default, navigation skips over values like nils, numbers and
keywords, which are not interesting to inspect. You can control this
behavior using the variable `cider-inspector-skip-uninteresting`.

The inspector buffer is automatically selected by default. You
can disable the auto selection with the variable
`cider-inspector-auto-select-buffer`.

You can set the amount of data shown by default with the variables
`cider-inspector-page-size`, `cider-inspector-max-coll-size`, and
`cider-inspector-max-atom-length`. The values can be adjusted for the current
inspector buffer using the `s`, `c`, and `a` keybindings.

If you enable `cider-inspector-fill-frame`, the inspector window fills its
frame.

== Additional Resources

* https://practicalli.github.io/spacemacs/evaluating-clojure/inspect.html[Using CIDER's Inspector in Spacemacs]
