= Support

CIDER currently has several official & unofficial support channels.

For questions, suggestions and support refer to one of them.  Please, don't
use the support channels to report issues, as this makes them harder to track.

== Mailing list

The https://groups.google.com/forum/#!forum/cider-emacs[official mailing list] is
hosted at Google Groups. It's a low-traffic list, so don't be too hesitant to subscribe.

== Freenode

We've got an unofficial Freenode channel - `#clojure-emacs`. It's not actively
monitored by the CIDER maintainers themselves, but still you can get support
from other CIDER users there.

== Slack

We've got an official https://clojurians.slack.com/[Clojurians Slack] -
`#cider`. This is usually be best way to get a handle on some of the maintainers
and interact with other CIDER users. The channel is very active! If you need an invite
you can go http://clojurians.net/[here].

There's also another channel named `#emacs` for generic Emacs discussions.

== Stackoverflow

We're also encouraging users to ask CIDER-related questions on StackOverflow.

When doing so you should use the
http://stackoverflow.com/questions/tagged/cider[cider] tag (ideally combined
with the tags `emacs` and `clojure`).

== Bountysource

If you're willing to pay for some feature to be implemented you can use
https://www.bountysource.com/teams/cider/issues[Bountysource] to place a
bounty for the work you want to be done.
