= ClojureCLR

== Current Status

You will get basic CIDER functionality with ClojureCLR. Two nREPL server options:

- https://github.com/clojure/clr.tools.nrepl[clr.tools.nrepl]: currently a port of https://github.com/babashka/babashka.nrepl[babashka.nrepl] to ClojureCLR.
- https://github.com/clojure/clr.tools.nrepl/tree/master/partial-nrepl-nrepl-port[port of nrepl/nrepl]: A non-working, work-in-progress port of nrepl/nrepl, which may
  ultimately better integrate with CIDER once CIDER's middleware (cider-nrepl) is also adapted/ported.

CIDER's support is basic because `cider-nrepl`, the middleware behind most of
CIDER's features, uses a lot of Java internally and would need to be ported to
ClojureCLR like any other Clojure library.

Alternatives to using CIDER with ClojureCLR include https://github.com/clojure-emacs/inf-clojure[inf-clojure] and https://github.com/nrepl/neat[neat].

== Usage

NOTE: Contributions welcome!

`cider-jack-in-universal` will jack into a clr.tools.nrepl server as long as a `deps-clr.edn` file
exists in the project directory, otherwise you may call `cider-jack-in-universal` with prefix
argument 6, by either `M-6` or `C-u 6` followed by `M-x cider-jack-in-universal`.

== Plans

In an ideal world we'll achieve the following objectives:

- feature parity between Clojure's nREPL implementation and `clr.tools.nrepl` (the project can use some help)
- adapting `cider-nrepl` for ClojureCLR (some of its codebase is JVM-specific)

Given that Bozhidar's knowledge of CLR and time are limited, it'd be great if we manage to find some volunteers to help with the
work that's needed in this direction. In particular it'd be amazing to complete `clr.tools.nrepl`, as the project needs relatively
little work to be fully usable.
